### ISSUE TITLE
un-eval behavior of strings with embedded newlines 

### ISSUE THREAD

**Issue by dmlb2000** [tiansh/un_eval.js#1]
The behavior of un-eval of strings with embedded newlines is untested. We should add a test to verify the behavior of un-eval is what's expected.

**Comment by tiansh** [comment]
All ASCII characters, including line breaks (CR, LF), had been covered by [line 74](https://github.com/tiansh/un_eval.js/blob/68d0f05e4bab52ee4d90cd479121a775dc41de5d/test/test.js#L74).

> stringItem('string ascii', String.fromCharCode.apply(String, [...Array(128)].map((_, i) => i)));

I believe this test case is enough for testing the behavior of handling newlines.
